"""
overhired — companion service

Start with:
    pip install -r requirements.txt
    python main.py

Or with custom port:
    python main.py --port 7878

Endpoints:
    GET  /health    — liveness probe used by the extension
    POST /generate  — build prompt, call AI, return cover letter (md + html)
    POST /save      — write cover_letter.md + cover_letter.html to disk
    POST /extract   — adaptive job extraction (cached parser or LLM-generated)
"""

from __future__ import annotations

import argparse
import hashlib
import html as _html
import logging
import re
import sys
import textwrap
from datetime import date
from pathlib import Path
from typing import Optional

import markdown as md_lib
import uvicorn
from fastapi import BackgroundTasks, Depends, FastAPI, Header, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

import analyzer as analyzer_module
import config as cfg_module
import ai_client as ai_module

# ── Boot ─────────────────────────────────────────────────────────────────────

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(name)s] %(levelname)s: %(message)s",
    stream=sys.stdout,
)
logger = logging.getLogger(__name__)

CFG = cfg_module.load()
AI  = ai_module.AIClient(CFG["ai"])

app = FastAPI(title="overhired companion", version="1.0.0")

# Allow the browser extension (chrome-extension:// / moz-extension://) to call
# us.  Restricting to extension-scheme origins prevents arbitrary web pages from
# using the companion as a file-write or AI-proxy primitive.
app.add_middleware(
    CORSMiddleware,
    allow_origin_regex=r"chrome-extension://[\w-]+|moz-extension://[\w-]+",
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)

# ── Auth ─────────────────────────────────────────────────────────────────────

def _require_token(x_overhired_token: Optional[str] = Header(default=None)) -> None:
    """Reject requests that don't carry the configured shared secret.

    Only enforced when ``auth_token`` is set in config.toml.  Leave it empty
    during initial setup; set it to a random string once you're ready to lock
    things down, then copy the same value to the extension's Settings.
    """
    expected = CFG.get("auth_token", "")
    if expected and x_overhired_token != expected:
        raise HTTPException(status_code=401, detail="Invalid or missing X-Overhired-Token")


# ── Request / Response models ─────────────────────────────────────────────────

class GenerateRequest(BaseModel):
    job_title:            str
    company:              str
    job_description:      str
    resume_text:          str = ""
    user_profile:         dict          = Field(default_factory=dict)
    global_instructions:  str           = ""
    per_job_instructions: str           = ""
    easter_egg:           bool          = False
    easter_egg_text:      Optional[str] = None
    # Optional per-request AI override from extension settings.
    # When provided these take precedence over the companion's config.toml.
    ai_provider:          Optional[str] = None
    ai_endpoint:          Optional[str] = None
    ai_model:             Optional[str] = None
    ai_key:               Optional[str] = None


class GenerateResponse(BaseModel):
    cover_letter_md:   str
    cover_letter_html: str


class SaveRequest(BaseModel):
    company:           str
    role:              str
    cover_letter_md:   str
    cover_letter_html: str
    job_description:   str = ""
    resume_text:       str = ""
    domain:            str = ""
    # output_dir intentionally removed from the public API — the companion
    # always writes under its configured output_dir to prevent arbitrary
    # file writes by any caller.


class SaveResponse(BaseModel):
    md_path:   str
    html_path: str
    job_id:    str


def _format_summary(data: dict, company: str, domain: str) -> str:
    """Format research_company() result as summary.md."""
    lines = [f"# Company Research — {company}", ""]
    if data.get("error"):
        lines += [f"> ⚠️ Could not fetch company data: {data['error']}", ""]
        lines += ["---", "*Generated by overhired*"]
        return "\n".join(lines)
    meta = []
    if data.get("industry"):
        meta.append(f"**Industry:** {data['industry']}")
    if data.get("size_stage"):
        meta.append(f"**Size/Stage:** {data['size_stage']}")
    if meta:
        lines.append("  ".join(meta))
    lines.append(f"**Generated:** {date.today()}  **Source:** {domain}")
    lines.append("")
    if data.get("overview"):
        lines += ["## Overview", data["overview"], ""]
    if data.get("products_services"):
        lines += ["## Products & Services"] + [f"- {p}" for p in data["products_services"]] + [""]
    if data.get("tech_stack_hints"):
        lines += ["## Tech Stack Hints"] + [f"- {t}" for t in data["tech_stack_hints"]] + [""]
    if data.get("culture_signals"):
        lines += ["## Culture Signals"] + [f"- {s}" for s in data["culture_signals"]] + [""]
    if data.get("mission_statement"):
        lines += ["## Mission", f'> {data["mission_statement"]}', ""]
    if data.get("red_flags"):
        lines += ["## 🚩 Red Flags"] + [f"- {f}" for f in data["red_flags"]] + [""]
    if data.get("green_flags"):
        lines += ["## ✅ Green Flags"] + [f"- {f}" for f in data["green_flags"]] + [""]
    if data.get("notable"):
        lines += ["## Notable", data["notable"], ""]
    lines += ["---", "*Generated by overhired*"]
    return "\n".join(lines)


def _format_score(data: dict, role: str, company: str) -> str:
    """Format score_job_fit() result as score.md."""
    score = data.get("score", 0)
    rec = data.get("recommendation", "Unknown")
    rec_emoji = {"Apply": "✅", "Apply with caveats": "⚠️", "Stretch role": "🔶", "Skip": "❌"}.get(rec, "")
    lines = [f"# Job Fit — {role} at {company}", ""]
    if data.get("error"):
        lines += [f"> ⚠️ Could not score: {data['error']}", ""]
        lines += ["---", "*Generated by overhired*"]
        return "\n".join(lines)
    lines += [f"## Score: {score}/10 — {rec} {rec_emoji}", ""]
    meta = []
    if data.get("experience_gap"):
        meta.append(f"**Experience gap:** {data['experience_gap']}")
    overq = data.get("overqualified_risk")
    if overq is not None:
        meta.append(f"**Overqualified risk:** {'Yes' if overq else 'No'}")
    meta.append(f"**Generated:** {date.today()}")
    lines += ["  ".join(meta), ""]
    if data.get("matching_skills"):
        lines += ["## ✅ Matching Skills"] + [f"- {s}" for s in data["matching_skills"]] + [""]
    if data.get("missing_skills"):
        lines += ["## ❌ Missing Skills"] + [f"- {s}" for s in data["missing_skills"]] + [""]
    if data.get("reasoning"):
        lines += ["## Honest Assessment", data["reasoning"], ""]
    lines += ["---", "*Generated by overhired*"]
    return "\n".join(lines)


def _format_insight(data: dict, role: str, company: str) -> str:
    """Format decode_jargon() result as insight.md."""
    verdict = data.get("verdict", "")
    verdict_emoji = {"Apply": "✅", "Apply with caution": "⚠️", "Skip": "❌"}.get(verdict, "")
    lines = [f"# Role Insights — {role} at {company}", ""]
    if verdict:
        lines += [f"**Verdict:** {verdict} {verdict_emoji}  **Generated:** {date.today()}", ""]
    if data.get("overall_vibe"):
        lines += [f"> {data['overall_vibe']}", ""]
    red = data.get("red_flags", [])
    green = data.get("green_flags", [])
    if red:
        lines += [
            "## 🚩 Red Flags",
            "",
            "| Phrase | What it really means |",
            "|--------|---------------------|",
        ]
        for f in red:
            lines.append(f"| {f.get('phrase', '')} | {f.get('reality', '')} |")
        lines.append("")
    if green:
        lines += [
            "## ✅ Green Flags",
            "",
            "| Phrase | What it signals |",
            "|--------|----------------|",
        ]
        for f in green:
            lines.append(f"| {f.get('phrase', '')} | {f.get('signal', '')} |")
        lines.append("")
    lines += ["---", "*Generated by overhired*"]
    return "\n".join(lines)


def _bg_write_summary(dest: Path, domain: str, company: str) -> None:
    logger.info("[analysis] summary.md starting — fetching %s", domain)
    try:
        data = analyzer_module.research_company(domain, company, AI)
        (dest / "summary.md").write_text(_format_summary(data, company, domain), encoding="utf-8")
        logger.info("[analysis] summary.md done for %s", company)
    except Exception as exc:
        logger.warning("[analysis] summary.md failed: %s", exc)


def _bg_write_score(dest: Path, job_description: str, resume_text: str, role: str, company: str) -> None:
    logger.info("[analysis] score.md starting for %s @ %s", role, company)
    try:
        data = analyzer_module.score_job_fit(job_description, resume_text, AI)
        (dest / "score.md").write_text(_format_score(data, role, company), encoding="utf-8")
        logger.info("[analysis] score.md done — score=%s recommendation=%s", data.get("score"), data.get("recommendation"))
    except Exception as exc:
        logger.warning("[analysis] score.md failed: %s", exc)


def _bg_write_insight(dest: Path, job_description: str, role: str, company: str) -> None:
    logger.info("[analysis] insight.md starting for %s @ %s", role, company)
    try:
        data = analyzer_module.decode_jargon(job_description, AI)
        (dest / "insight.md").write_text(_format_insight(data, role, company), encoding="utf-8")
        logger.info("[analysis] insight.md done — verdict=%s red_flags=%d",
                    data.get("verdict"), len(data.get("red_flags", [])))
    except Exception as exc:
        logger.warning("[analysis] insight.md failed: %s", exc)


# ── Endpoints ─────────────────────────────────────────────────────────────────

@app.get("/health")
def health():
    ai_ok, ai_model = AI.health_check()
    return {
        "status":      "ok",
        "ai_provider":  CFG["ai"]["provider"],
        "ai_model":     ai_model,
        "ai_endpoint":  CFG["ai"]["endpoint"],
        "ai_reachable": ai_ok,
    }


@app.post("/generate", response_model=GenerateResponse)
def generate(req: GenerateRequest, _: None = Depends(_require_token)):
    # Build a per-request AIClient when the extension overrides provider/model/
    # endpoint/key; otherwise reuse the global client to avoid the overhead of
    # constructing a new one on every request.
    ai = AI
    if req.ai_provider or req.ai_model or req.ai_endpoint:
        override = dict(CFG["ai"])
        if req.ai_provider: override["provider"] = req.ai_provider
        if req.ai_endpoint: override["endpoint"] = req.ai_endpoint.rstrip("/")
        if req.ai_model:    override["model"]    = req.ai_model
        if req.ai_key:      override["api_key"]  = req.ai_key
        ai = ai_module.AIClient(override)

    if not req.resume_text:
        req = req.model_copy(update={"resume_text": cfg_module.load_resume_text(CFG)})

    logger.info("[generate] %s @ %s | resume=%d chars | jd=%d chars",
                req.job_title, req.company, len(req.resume_text), len(req.job_description))
    system_prompt = _build_system_prompt()
    user_prompt   = _build_user_prompt(req)

    try:
        logger.info("[generate] calling AI (%s %s)...", CFG['ai']['provider'], CFG['ai']['model'])
        raw = ai.generate(system_prompt, user_prompt)
        logger.info("[generate] AI done — response %d chars", len(raw))
    except ai_module.AIError as exc:
        logger.error("[generate] AI error: %s", exc)
        raise HTTPException(status_code=502, detail=str(exc))

    # Normalise - some models wrap output in markdown fences
    cover_md = _unwrap_fences(raw)
    cover_md = _clean_output(cover_md)

    # Append easter egg HTML comment if requested
    if req.easter_egg:
        egg_text = req.easter_egg_text or CFG["cover_letter"]["easter_egg_text"]
        # Inject company/role into the egg text if placeholders exist
        egg_text = egg_text.replace("{company}", req.company).replace("{role}", req.job_title)
        comment_lines = "\n".join(f"  {l}" for l in egg_text.splitlines())
        cover_md += f"\n\n<!--\n{comment_lines}\n-->\n"

    cover_html = _md_to_html(cover_md, req.company, req.job_title)

    return GenerateResponse(cover_letter_md=cover_md, cover_letter_html=cover_html)


@app.post("/save", response_model=SaveResponse)
def save(req: SaveRequest, background_tasks: BackgroundTasks, _: None = Depends(_require_token)):
    out_root = Path(CFG["output_dir"]).expanduser()
    company  = _safe_name(req.company)
    role     = _safe_name(req.role)
    dest     = out_root / company / role
    dest.mkdir(parents=True, exist_ok=True)

    md_path   = dest / "cover_letter.md"
    html_path = dest / "cover_letter.html"

    md_path.write_text(req.cover_letter_md, encoding="utf-8")
    html_path.write_text(req.cover_letter_html, encoding="utf-8")
    logger.info("[save] cover_letter written → %s", dest)

    resume_text = req.resume_text or cfg_module.load_resume_text(CFG)

    if req.job_description:
        logger.info("[save] queuing insight.md background task")
        background_tasks.add_task(_bg_write_insight, dest, req.job_description, req.role, req.company)
        if resume_text:
            logger.info("[save] queuing score.md background task")
            background_tasks.add_task(_bg_write_score, dest, req.job_description, resume_text, req.role, req.company)
        else:
            logger.info("[save] no resume_text — skipping score.md")
    if req.domain:
        logger.info("[save] queuing summary.md background task (domain=%s)", req.domain)
        background_tasks.add_task(_bg_write_summary, dest, req.domain, req.company)
    else:
        logger.info("[save] no domain — skipping summary.md")

    job_id = hashlib.md5(str(dest).encode()).hexdigest()[:12]
    return SaveResponse(md_path=str(md_path), html_path=str(html_path), job_id=job_id)


# ── /jobs/{job_id}/files ──────────────────────────────────────────────────────

@app.get("/jobs/{job_id}/files")
def job_files(job_id: str, _: None = Depends(_require_token)):
    """Poll which analysis files have been written for a given job_id."""
    out_root = Path(CFG["output_dir"]).expanduser()
    dest: Path | None = None
    if out_root.exists():
        for company_dir in out_root.iterdir():
            if not company_dir.is_dir():
                continue
            for role_dir in company_dir.iterdir():
                if not role_dir.is_dir():
                    continue
                if hashlib.md5(str(role_dir).encode()).hexdigest()[:12] == job_id:
                    dest = role_dir
                    break
            if dest:
                break
    if dest is None:
        raise HTTPException(status_code=404, detail=f"job_id {job_id!r} not found")
    return {
        "job_id": job_id,
        "cover_letter": (dest / "cover_letter.md").exists(),
        "summary": (dest / "summary.md").exists(),
        "score": (dest / "score.md").exists(),
        "insight": (dest / "insight.md").exists(),
    }


# ── /extract ──────────────────────────────────────────────────────────────────

class ExtractRequest(BaseModel):
    domain:    str = Field(..., description="Hostname, e.g. 'linkedin.com'")
    page_text: str = Field(..., description="document.body.innerText (max 12 000 chars)")


class ExtractResponse(BaseModel):
    title:       str = ""
    company:     str = ""
    description: str = ""
    location:    str = ""


@app.post("/extract", response_model=ExtractResponse)
def extract_job(req: ExtractRequest, _: None = Depends(_require_token)):
    import extractor
    logger.info("[extract] domain=%s page_text=%d chars", req.domain, len(req.page_text))
    result = extractor.extract(req.domain, req.page_text, AI)
    logger.info("[extract] result: title=%r company=%r", result.get("title",""), result.get("company",""))
    return ExtractResponse(**result)


@app.get("/parsers")
def list_parsers_endpoint(_: None = Depends(_require_token)):
    from tool_server import list_parsers
    return list_parsers()


@app.delete("/parsers/{domain}")
def delete_parser_endpoint(domain: str, _: None = Depends(_require_token)):
    from tool_server import delete_parser
    result = delete_parser(domain)
    if "error" in result:
        raise HTTPException(status_code=404, detail=result["error"])
    return result


# ── Prompt builders ───────────────────────────────────────────────────────────

def _build_system_prompt() -> str:
    max_words = CFG["cover_letter"].get("max_words", 450)
    language  = CFG["cover_letter"].get("language", "English")
    return textwrap.dedent(f"""\
        You are an expert cover letter writer. Your task is to produce a
        personalized, professional cover letter in Markdown format.

        Guidelines:
        - Language: {language}
        - Target length: {max_words} words (be concise and impactful)
        - Tone: confident, warm, genuine - never sycophantic
        - Start with a salutation (e.g. "Dear Hiring Team,")
        - Highlight 2-3 specific skills or experiences from the resume that
          directly match the job requirements
        - End with a professional closing and the applicant's name
        - Do NOT include a date, subject line, or postal addresses
        - Output ONLY the cover letter - no preamble, no commentary
        - Use ONLY plain ASCII characters. No em dashes, en dashes, smart
          quotes, curly apostrophes, ellipsis characters, or any Unicode
          punctuation. Use a plain hyphen (-) instead of any dash.
        - Do NOT add trailing spaces after sentences or at the end of lines.
    """)


def _build_user_prompt(req: GenerateRequest) -> str:
    parts = [
        f"## Role\n{req.job_title} at {req.company}",
        f"## Job Description\n{req.job_description.strip()}",
        f"## My Resume\n{req.resume_text.strip()}",
    ]

    profile = req.user_profile
    if profile:
        profile_lines = "\n".join(
            f"- {k}: {v}" for k, v in profile.items() if v
        )
        parts.append(f"## My Profile\n{profile_lines}")

    if req.global_instructions.strip():
        parts.append(f"## Global Instructions (always apply)\n{req.global_instructions.strip()}")

    if req.per_job_instructions.strip():
        parts.append(
            f"## Specific Instructions for This Application\n"
            f"{req.per_job_instructions.strip()}"
        )

    parts.append("Write the cover letter now:")
    return "\n\n".join(parts)


# ── HTML export ───────────────────────────────────────────────────────────────

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Cover Letter — {role} at {company}</title>
  <style>
    body {{
      font-family: Georgia, 'Times New Roman', serif;
      max-width: 740px;
      margin: 60px auto;
      padding: 0 24px;
      color: #1a1a1a;
      line-height: 1.75;
      font-size: 16px;
    }}
    p {{ margin: 0 0 1em; }}
    strong {{ font-weight: 600; }}
  </style>
</head>
<body>
{body}
</body>
</html>
"""

def _md_to_html(cover_md: str, company: str, role: str) -> str:
    # Split off any trailing HTML comment (easter egg) before converting,
    # then re-append it so it stays outside the converted <p> tags.
    egg_comment = ""
    md_body = cover_md

    # Match the last HTML comment in the document — must be anchored at end.
    # Pattern avoids greedy matching across multiple comments by requiring no '-->'
    # inside the comment body (standard HTML comment constraint).
    comment_match = re.search(r"\n(<!--(?:[^-]|-(?!->))*-->)\s*$", cover_md)
    if comment_match:
        egg_comment = "\n" + comment_match.group(1)
        md_body = cover_md[: comment_match.start()]

    body_html = md_lib.markdown(md_body)
    full_body = body_html + egg_comment

    return _HTML_TEMPLATE.format(
        company=_html.escape(company),
        role=_html.escape(role),
        body=full_body,
    )


# ── Helpers ───────────────────────────────────────────────────────────────────

def _clean_output(text: str) -> str:
    """Strip trailing whitespace from every line and replace non-ASCII punctuation."""
    # Common non-ASCII punctuation replacements
    replacements = [
        ('—', '-'),   # em dash
        ('–', '-'),   # en dash
        ('‒', '-'),   # figure dash
        ('‘', "'"),   # left single quotation mark
        ('’', "'"),   # right single quotation mark / apostrophe
        ('“', '"'),   # left double quotation mark
        ('”', '"'),   # right double quotation mark
        ('…', '...'), # horizontal ellipsis
        (' ', ' '),   # non-breaking space
    ]
    for src, dst in replacements:
        text = text.replace(src, dst)
    # Strip trailing whitespace from every line (catches "sentence.  " patterns)
    lines = [line.rstrip() for line in text.splitlines()]
    return '\n'.join(lines).strip()


def _unwrap_fences(text: str) -> str:
    """Remove ```markdown … ``` wrappers that some models add."""
    text = text.strip()
    if text.startswith("```"):
        lines = text.splitlines()
        # Drop first line (``` or ```markdown) and last ``` line
        inner = lines[1:]
        if inner and inner[-1].strip() == "```":
            inner = inner[:-1]
        return "\n".join(inner).strip()
    return text


def _safe_name(name: str) -> str:
    """Convert a company/role name to a safe directory component."""
    name = name.strip()
    name = re.sub(r"[^\w\s-]", "", name)       # remove special chars
    name = re.sub(r"[\s_]+", "-", name)        # spaces → hyphens
    name = name.strip("-")
    return name[:64] or "unknown"              # cap length


# ── Entry point ───────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(prog="overhired-companion")
    parser.add_argument("--port",      type=int, default=CFG.get("companion_port", 7878))
    parser.add_argument("--host",      default="127.0.0.1")
    parser.add_argument("--reload",    action="store_true", help="Dev mode auto-reload")
    parser.add_argument("--log-level", default="info",
                        choices=["debug", "info", "warning", "error"],
                        help="Log verbosity (default: info)")
    args = parser.parse_args()

    # Apply log level to all overhired loggers
    level = getattr(logging, args.log_level.upper(), logging.INFO)
    logging.getLogger().setLevel(level)

    print(f"\noverhired companion  |  http://{args.host}:{args.port}")
    print(f"  AI provider  : {CFG['ai']['provider']}  ({CFG['ai']['endpoint']})")
    print(f"  AI model     : {CFG['ai']['model']}")
    print(f"  Output dir   : {CFG['output_dir']}")
    print(f"  Log level    : {args.log_level}")

    # List cached parsers at startup
    from tool_server import list_parsers
    cached = list_parsers()
    if cached["count"]:
        print(f"  Cached parsers ({cached['count']}):", ", ".join(p["domain"] for p in cached["parsers"]))
    else:
        print("  Cached parsers: none (will generate on first scan of each site)")
    print()

    uvicorn.run(
        "main:app",
        host=args.host,
        port=args.port,
        reload=args.reload,
        log_level=args.log_level,
    )


if __name__ == "__main__":
    main()
